branches:
  only:
  - master
  - "/^v.*$/"
language: python
sudo: false
python:
- 3.3
- 3.4
- 3.5
- 3.6
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
- pip install -e .
script:
- pytest -v
